### PR TITLE
Enhancement/breaker config

### PR DESCRIPTION
**Pull request by coders-kitchen**
This PR adds application properties configurable breakers.

At the moment it supports _timeout_, _delay_, _success threshold_, _failure threshold_.

Further configs can be easily added in the future.

This PR is based on ehancement/method-annotation

### CODE REVIEW

**Comment by duergner** [comment]
Have you considered to use a definition of durations similar to the ones used on our [Put it to REST](https://github.com/zalando-stups/put-it-to-rest) project?

Furthermore it would be really great if we could assess the solution regarding how easy it would be to incorporate it with [Put it to REST](https://github.com/zalando-stups/put-it-to-rest), i.e. have the breaker and retry specific configuration done as part of the `rest.clients.CLIENT_NAME` like e.g. `rest.clients.CLIENT_NAME.breaker` and `rest.clients.CLIENT_NAME.retry`.

[Put it to REST](https://github.com/zalando-stups/put-it-to-rest) could than have support for e.g. both Hystrix and Failsafe and configure them depending on what is present on the classpath.

@whiskeysierra WDYT?

**Comment by whiskeysierra** [comment]
That is already on my roadmap. First step would be to have a `riptide-failsafe` module that provides a `FailsafePlugin`: zalando/riptide#218

The next step after that would be pretty much what you described: Allow to configure retries and circuit breakers per client in the application.yaml:

```yaml
rest.clients:
  example:
    failsafe: # only needed if we keep hystrix as an alternative, not sure if I actually want to
      retry:
        fixed-delay: 1 second
        exponentional-backoff:
          delay: 500 millis
          max-delay: 3 seconds
          delay-factor: 2 # default
        max-retries: 3
        max-duration: 5 seconds
        jitter: 0.1
      circuit-breaker:
        failure-threshold: 5
        delay: 1 minute
        success-threshold: 3 out of 5
```

**Comment by duergner** [comment]
Sounds like there is quite some collaboration potential between [Put it to REST!](github.com/zalando-incubator/put-it-to-rest), [Failsafe Actuator](https://github.com/zalando-incubator/failsafe-actuator) and [Riptide](https://github.com/zalando/riptide).

As they are all Zalando projects it would really be great if we could find a common shared solution here IMHO.

**Comment by whiskeysierra** [comment]
@duergner riptide and put-it-to-rest are already very closely related. Put-it-to-rest is basically the handy-automagic-configuration-tool for riptide. Adding to my simple roadmap above, if we just use the `CircuitBreakerRegistry` inside of put-it-to-rest when we create a circuit breaker per client, then we already made the connection.

**Comment by whiskeysierra** [comment]
zalando-stups/put-it-to-rest#71

**Comment by coders-kitchen** [comment]
@duergner I'm back from vacation. 

Good idea, will adapt the definition style for durations as well as the ones for thresholds to make it streamlined.

**Comment by coders-kitchen** [comment]
@MALPI should we merge it?

**Pull request closed without merging**
