### PR TITLE
Changed urls

### PR DESCRIPTION
**Pull request by keramiozsoy**
I added correct links :)

### CODE REVIEW

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
Thanks for your PR, I will take care ASAP.

**Comment by keramiozsoy** [comment]
travis-ci can not build @MALPI

**Comment by musiKk** [comment]
👍

**Comment by MALPI** [comment]
:+1:

**Comment by musiKk** [comment]
👍

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
:+1:

**Comment by keramiozsoy** [comment]
👍

**Pull request merged**
