### PR TITLE
by accident we had the asserts in the target jar...

### PR DESCRIPTION
**Pull request by JonasJurczok**
By accident I put the assert dependency in the wrong scope...

### CODE REVIEW

**Comment by MALPI** [comment]
Hey, @JonasJurczok thanks for your PR. I will push a new version as soon as I return to the office.

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
@mmodabber please review

**Comment by mmodabber** [comment]
:+1:

**Comment by duergner** [comment]
:+1:

**Pull request merged**
